
//////////////////////////////////////////////////////////////////////
// Automatically generated by Bradley's GumpStudio and roadmaster's 
// exporter.dll,  Special thanks goes to Daegon whose work the exporter
// was based off of, and Shadow wolf for his Template Idea.
//////////////////////////////////////////////////////////////////////
#define RunUo2_0

using System;
using Server;
using Server.Gumps;
using Server.Network;
using Server.Commands;
using Server.Mobiles;
using Server.Fronteira.Classes;
using Server.Fronteira.Talentos;

namespace Server.Gumps
{
    public class GumpTalento : Gump
    {
        public GumpTalento(PlayerMobile from, OpcaoTalentos opcoes) : base(0, 0)
        {
            this.Closable = true;
            this.Disposable = true;
            this.Dragable = true;
            this.Resizable = false;

            AddPage(0);
            AddBackground(244, 75, 512, 259, 1579);
            AddHtml(420, 104, 155, 21, @"Escolha um Talento", (bool)false, (bool)false);
            AddBackground(582, 155, 143, 137, 9350);
            AddBackground(427, 155, 143, 137, 9350);
            AddBackground(274, 156, 143, 137, 9350);
   
            var t1 = DefTalentos.GetDef(opcoes.T1);
            var t2 = DefTalentos.GetDef(opcoes.T2);
            var t3 = DefTalentos.GetDef(opcoes.T3);

            AddImage(630, 179, t3.Icone);
            AddImage(476, 178, t2.Icone);
            AddImage(320, 178, t1.Icone);

            AddHtml(310, 157, 69, 21, t1.Nome, (bool)false, (bool)false);
            AddHtml(464, 156, 69, 21, t2.Nome, (bool)false, (bool)false);
            AddHtml(618, 156, 69, 21, t3.Nome, (bool)false, (bool)false);
            AddHtml(279, 223, 129, 49, t1.Desc1, (bool)false, (bool)false);
            AddHtml(433, 223, 129, 49, t2.Desc1, (bool)false, (bool)false);
            AddHtml(586, 221, 129, 49, t3.Desc1, (bool)false, (bool)false);
            AddButton(307, 279, 247, 248, 0, GumpButtonType.Reply, 0);
            AddButton(467, 278, 247, 248, 0, GumpButtonType.Reply, 0);
            AddButton(624, 280, 247, 248, 0, GumpButtonType.Reply, 0);

            AddImage(272, 135, 50);
            AddImage(415, 135, 50);
            AddImage(455, 136, 50);
            AddImage(583, 137, 50);

            AddImage(234, 68, 10460);
            AddImage(738, 69, 10460);
            AddImage(738, 313, 10460);
            AddImage(235, 312, 10460);



        }



        public override void OnResponse(NetState sender, RelayInfo info)
        {
            Mobile from = sender.Mobile;

            switch (info.ButtonID)
            {
                case 0:
                    {

                        break;
                    }

            }
        }
    }
}
