
//////////////////////////////////////////////////////////////////////
// Automatically generated by Bradley's GumpStudio and roadmaster's 
// exporter.dll,  Special thanks goes to Daegon whose work the exporter
// was based off of, and Shadow wolf for his Template Idea.
//////////////////////////////////////////////////////////////////////
#define RunUo2_0

using System;
using Server;
using Server.Gumps;
using Server.Network;
using Server.Commands;
using Server.Ziden;
using Server.Leilaum;

namespace Server.Gumps
{
    public class DisenchantConfirm : Gump
    {
        Mobile caller;
        Item item;
        int cristais;

        public bool Valid()
        {
            if (item.Deleted || item.RootParent != caller)
                return false;
            return true;
        }

        public DisenchantConfirm(Mobile from, int essencias, Item item) : base(0, 0)
        {

            caller = from;
            this.item = item;
            this.cristais = essencias;

            if (!from.IsCooldown("dicaen"))
            {
                from.SetCooldown("dicaen");
                from.SendMessage(78, "Quanto mais Imbuing voce tiver, e melhor o item que voce desencantar for mais essencias voce ira ganhar !");
            }

            this.Closable = true;
            this.Disposable = true;
            this.Dragable = true;
            this.Resizable = false;

            AddPage(0);
            AddBackground(102, 82, 467, 229, 9200);
            AddBackground(113, 93, 180, 205, 9380);
            AddHtml(153, 96, 119, 22, @"Desencantar", (bool)false, (bool)false);
            AddHtml(133, 134, 139, 127, @"Voce ira destruir o item para converter em essencias !", (bool)false, (bool)false);
            AddItem(514, 118, 11736);
            AddButton(391, 273, 247, 248, (int)Buttons.Button1, GumpButtonType.Reply, 0);
            AddHtml(308, 245, 221, 26, @"Clique em OK para encantar", (bool)false, (bool)false);
            AddBackground(352, 62, 100, 100, 9250);
            AddImage(392, 168, 4035);
            AddBackground(308, 189, 187, 46, 302);
            AddHtml(360, 202, 128, 22, cristais+" Essencias", (bool)false, (bool)false);
            AddItem(328, 212, 7847);
            AddItem(330, 201, 7847);
            AddItem(321, 211, 7847);
            AddItem(322, 199, 7847);

            NewAuctionGump.AddItemCentered(352, 62, 100, 100, item.ItemID, item.Hue, this);
            AddItemProperty(item.Serial);

        }

        public enum Buttons
        {
            Nop,
            Button1,
        }


        public override void OnResponse(NetState sender, RelayInfo info)
        {
            Mobile from = sender.Mobile;

            switch (info.ButtonID)
            {
                case (int)Buttons.Button1:
                    {
                        if(!Valid())
                        {
                            from.SendMessage("O item precisa estar em sua mochila");
                            return;
                        }
                        var mult = 1;
                        if (cristais > 10)
                            mult += 10;
                        if (cristais > 20)
                            mult += 20;

                        from.OverheadMessage("* desencantou item *");
                        from.PlaySound(0x57);
                        from.PlayAttackAnimation();
                        from.FixedParticles(0x376A, 9, 32, 5030, EffectLayer.Waist);
                        from.CheckSkillMult(SkillName.Imbuing, 0, 100, mult);
                        from.SendMessage("Voce transformou o item em " + cristais + " de essencia");
                        item.Delete();
                        var essencia = new EssenciaMagica();
                        essencia.Amount = cristais;
                        from.PlaceInBackpack(essencia);

                        break;
                    }

            }
        }
    }
}
