
//////////////////////////////////////////////////////////////////////
// Automatically generated by Bradley's GumpStudio and roadmaster's 
// exporter.dll,  Special thanks goes to Daegon whose work the exporter
// was based off of, and Shadow wolf for his Template Idea.
//////////////////////////////////////////////////////////////////////

using System;
using Server;
using Server.Gumps;
using Server.Network;
using Server.Commands;
using Server.Items;

namespace Server.Gumps
{
    public class OndeIrGump : Gump
    {
        Mobile caller;

        public static void Initialize()
        {
            CommandSystem.Register("ondeir", AccessLevel.Player, new CommandEventHandler(_OnCommand));
        }

        [Usage("ondeir")]
        [Description("Makes a call to your custom gump.")]
        public static void _OnCommand(CommandEventArgs e)
        {
            if (e.Mobile.HasGump(typeof(OndeIrGump)))
                e.Mobile.CloseGump(typeof(OndeIrGump));
            e.Mobile.SendGump(new OndeIrGump(e.Mobile));
        }

        public OndeIrGump(Mobile from) : this()
        {
            caller = from;
        }

        public OndeIrGump() : base(0, 0)
        {
            this.Closable = true;
            this.Disposable = true;
            this.Dragable = true;
            this.Resizable = false;

            AddPage(0);
            AddImage(447, 225, 30500);
            AddBackground(463, 236, 414, 100, 30536);
            AddHtml(594, 273, 165, 26, @"<CENTER>Encontre seu Destino</CENTER>", (bool)true, (bool)false);
            AddBackground(861, 213, 295, 484, 9390);
            AddImage(888, 254, Utility.Random(30567, 15));
            AddButton(541, 602, 2151, 2151, (int)Buttons.NPCS, GumpButtonType.Reply, 0);
            AddHtml(483, 573, 152, 23, @"<CENTER>NPCS</CENTER>", (bool)true, (bool)false);
            AddHtml(704, 572, 152, 23, @"<CENTER>AVENTURAS</CENTER>", (bool)true, (bool)false);
            AddButton(763, 600, 2151, 2151, (int)Buttons.Aventuras, GumpButtonType.Reply, 0);
            AddHtml(483, 343, 152, 23, @"<CENTER>DUNGEONS</CENTER>", (bool)true, (bool)false);
            AddButton(541, 373, 2151, 2151, (int)Buttons.Dungeons, GumpButtonType.Reply, 0);

            AddHtml(483, 343+100, 152, 23, @"<CENTER>FACTIONS</CENTER>", (bool)true, (bool)false);
            AddButton(541, 373+100, 2151, 2151, (int)Buttons.Factions, GumpButtonType.Reply, 0);

            AddHtml(700, 343, 152, 23, @"<CENTER>PARAR BUSCA</CENTER>", (bool)true, (bool)false);
            AddButton(763, 369, 2151, 2151, (int)Buttons.Parar, GumpButtonType.Reply, 0);

            AddImage(654, 427, 39830);
        }

        public enum Buttons
        {
            NPCS = 1,
            Aventuras = 2,
            Dungeons = 3,
            Factions = 4,
            Parar = 5
        }


        public override void OnResponse(NetState sender, RelayInfo info)
        {
            Mobile from = sender.Mobile;

            switch (info.ButtonID)
            {
                case (int)Buttons.NPCS:
                    {
                        from.CloseAllGumps();
                        from.SendGump(new NPCSGump(from));
                        break;
                    }
                case (int)Buttons.Aventuras:
                    {
                        from.CloseAllGumps();
                        from.SendGump(new MissoesGump(from));
                        break;
                    }
                case (int)Buttons.Factions:
                    {
                        from.CloseAllGumps();
                        from.SendGump(new ListaFactionsGump(from));
                        from.SendMessage(78, "Factions sao grupos PvP que qualquer player pode entrar. Voce podera ser atacado em cidades por outras factions. Factions podem roubar as pedras de sigilo de cidades para domina-la. Factions elegem um comandante a cada duas semanas, e este pode nomear um Sherife para colocar guardas e um Ministro para cuidar da taxacao das cidades.");
                        break;
                    }
                case (int)Buttons.Dungeons:
                    {
                        from.SendGump(new DungeonsGump(from));
                        break;
                    }
                case (int)Buttons.Parar:
                    {
                        if (from.QuestArrow != null)
                        {
                            from.QuestArrow.Stop();
                            from.QuestArrow = null;
                            from.SendMessage("Voce parou sua busca");
                        }
                        else
                        {
                            from.SendMessage("Voce nao esta buscando nada");
                        }
                        break;
                    }
            }
        }
    }
}
